### ISSUE TITLE
Another trick that might interest you

### ISSUE THREAD

**Issue by Juke34** [danrlu/Nextflow_cheatsheet#2]
How to parallelize the work from a path to all file it contains (filtered by extension)
```
/*
 * From folder path get all file ending with extension
 * Input: 2=> path, extension
 * Ourput: 1 =>  list
 */
process get_files_by_extension {
	
  input:
      path(folder_path)
      val(extension)

  output:
      file("${folder_path}/*${extension}")

  script:
	"""
	"""
}
```

**Comment by danrlu** [comment]
Thanks for the suggestion!!

I think it would work the same as: 
`output_ch = Channel.fromPath("${folder_path}/*${extension}")`
without going through a process. Each file will have 1 parallel execution. 

I think this is a very common task so Nextflow ppl built it into the [default behavior](https://www.nextflow.io/docs/latest/channel.html#frompath) of `Channel.fromPath` to save the users some trouble :D

**Comment by Juke34** [comment]
I don't think we talk about the same thing. 
In your case Channel.fromPath takes a path string and creates a channel
In my case I deal with a channel that contains a path type element

**Comment by danrlu** [comment]
Ohh I think I see what you're saying. I tend to do this type of channel operations outside of processes, but It's interesting idea to modify them through processes. I'll keep an eye out for such applications. 

Thanks!
